CREATE DATABASE IF NOT EXISTS function_scout;

CREATE TABLE IF NOT EXISTS WebService (
	id INT PRIMARY KEY AUTO_INCREMENT,
	githubUrl VARCHAR(512) NOT NULL,
	createDT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    UNIQUE(githubUrl)
);

CREATE TABLE IF NOT EXISTS WebServiceStatus (
	id INT PRIMARY KEY AUTO_INCREMENT,
	githubUrl VARCHAR(512) NOT NULL,
	status TINYINT(3) NOT NULL,
	message VARCHAR(512) NULL,
	createDT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
	updateDT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS Dependency (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(512) NOT NULL,
	version VARCHAR(64) NULL,
	type TINYINT(2) NULL,
	createDT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
	updateDT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
	UNIQUE(name, version)
);

CREATE TABLE WebServiceDependency (
    id INT PRIMARY KEY AUTO_INCREMENT,
    serviceId INT NOT NULL,
    dependencyId INT NOT NULL,
    FOREIGN KEY (serviceId) REFERENCES WebService(id),
    FOREIGN KEY (dependencyId) REFERENCES Dependency(id)
);